/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        'on-tertiary': '#ffffff',
        'secondary': '#565e74',
        'surface-container-high': '#e6e8ea',
        'surface-container-lowest': '#ffffff',
        'inverse-on-surface': '#eff1f3',
        'on-surface-variant': '#434655',
        'surface-tint': '#0053db',
        'tertiary-container': '#8343f4',
        'on-error-container': '#93000a',
        'error-container': '#ffdad6',
        'primary': '#004ac6',
        'surface-variant': '#e0e3e5',
        'primary-fixed-dim': '#b4c5ff',
        'on-secondary-fixed': '#131b2e',
        'on-error': '#ffffff',
        'on-secondary-container': '#5c647a',
        'on-primary-fixed-variant': '#003ea8',
        'error': '#ba1a1a',
        'on-primary': '#ffffff',
        'on-primary-fixed': '#00174b',
        'on-primary-container': '#eeefff',
        'on-tertiary-fixed': '#25005a',
        'tertiary-fixed': '#eaddff',
        'surface': '#f7f9fb',
        'outline-variant': '#c3c6d7',
        'surface-bright': '#f7f9fb',
        'secondary-fixed': '#dae2fd',
        'on-tertiary-fixed-variant': '#5a00c6',
        'primary-container': '#2563eb',
        'surface-dim': '#d8dadc',
        'tertiary': '#6a1edb',
        'surface-container-highest': '#e0e3e5',
        'background': '#f7f9fb',
        'on-secondary-fixed-variant': '#3f465c',
        'outline': '#737686',
        'secondary-container': '#dae2fd',
        'surface-container-low': '#f2f4f6',
        'secondary-fixed-dim': '#bec6e0',
        'on-background': '#191c1e',
        'inverse-primary': '#b4c5ff',
        'on-surface': '#191c1e',
        'tertiary-fixed-dim': '#d2bbff',
        'primary-fixed': '#dbe1ff',
        'on-secondary': '#ffffff',
        'inverse-surface': '#2d3133',
        'surface-container': '#eceef0',
        'on-tertiary-container': '#f7edff',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
    },
  },
  plugins: [],
}
